name: Build and deploy ASP.Net Core app to Azure Web App - DateApp-ng-net

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      # Шаг для вывода текущей директории и содержимого репозитория
      - name: Display current directory and list files
        run: |
          echo "Current directory:"
          pwd
          echo "List of files:"
          ls -la

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      # Проверка правильности пути до .sln
      - name: Verify solution file exists
        run: |
          if [ -f DatingApp.sln ]; then echo "Solution file found"; else echo "Solution file NOT found"; fi

      # Попробуем указать полный путь, если файл в корне
      - name: Restore dependencies
        run: dotnet restore ./DatingApp.sln

      - name: Build with dotnet
        run: dotnet build ./DatingApp.sln --configuration Release

      - name: Publish with dotnet
        run: dotnet publish ./DatingApp.sln --configuration Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.__clientidsecretname__ }}
          tenant-id: ${{ secrets.__tenantidsecretname__ }}
          subscription-id: ${{ secrets.__subscriptionidsecretname__ }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'DateApp-ng-net'
          slot-name: 'Production'
          package: .
